services:
  
  esortition-app:
    build: .
    environment:
      - FLASK_APP=/esortition-app/app.py
    ports:
      - "5001:5000"
  
  election_mgmt_service-app:
    build: ./election_mgmt_service
    environment:
      - FLASK_APP=/election_mgmt_service-app/election_service.py
      - DATABASE_URL=sqlite:///db.sqlite
    ports:
      - '3000:3000'
    volumes:
      - ./election_mgmt_service:/election_mgmt_service-app
      - ./data:/data  # Mount a volume to persist the SQLite database file
  
  microservice1-app:
    build: ./microservice1
    environment:
      - FLASK_APP=/microservice1-app/micro_app.py
    ports:
      - "5002:5001"

  microservice2-app:
    build: ./microservice2
    environment:
      - FLASK_APP=/microservice2-app/micro_app.py
    ports:
      - "5003:5002"

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: esortition_voting