version: '3.8'
services:
  esortition-app:
    build: .
    environment:
      - FLASK_APP=/esortition-app/app.py
    ports:
      - '5001:5000'
    volumes:
      - .:/esortition-app

  voting_service-app:
    build: ./voting_service
    environment:
      - FLASK_APP=/voting_service-app/voting_app.py
      - DATABASE_URL=postgresql://postgres:postgres@db/esortition_voting
    ports:
      - '5002:5001'
    volumes:
      - ./voting_service:/voting_service-app
    depends_on:
      - db

  microservice2-app:
    build: ./microservice2
    environment:
      - FLASK_APP=/microservice2-app/micro_app.py
    ports:
      - '5003:5002'
    volumes:
      - ./microservice2:/microservice2-app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esortition_voting
  # ports:
  #   - '5432:5432'
