version: '3.8'
services:
  admin_app-app:
    build: ./admin_app
    environment:
      - FLASK_APP=/admin_app-app/app.py
    ports:
      - '5001:5000'
    volumes:
      - ./admin_app:/admin_app-app

  voting_app-app:
    build: ./voting_app
    environment:
      - FLASK_APP=/voting_app-app/voting_app.py
      # - DATABASE_URL=postgresql://postgres:postgres@db/esortition_voting
    ports:
      - '5002:5001'
    volumes:
      - ./voting_app:/voting_app-app
    # depends_on:
    #   - db

  # Voting Microservice

  voting_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: esortition_voting

  voting_manager-service:
    build: ./voting_manager
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@voting_db/esortition_voting
      - FASTAPI_APP=/voting_manager-service/voting_manager_service.py
      # - FLASK_APP=/voting_manager-app/voting_manager_service.py

    ports:
      - '5003:5002'
    volumes:
      - ./voting_manager:/voting_manager-service
    depends_on:
      - voting_db

  # ports:
  #   - '5432:5432'
