version: '3.8'
services:
  esortition-app:
    build: .
    environment:
      - FLASK_APP=/esortition-app/app.py
    ports:
      - '5001:5000'
    volumes:
      - .:/esortition-app

  microservice1-app:
    build: ./microservice1
    environment:
      - FLASK_APP=/voting_service-app/voting_app.py
    ports:
      - '5002:5001'
    volumes:
      - ./voting_service:/voting_service-app

  microservice2-app:
    build: ./microservice2
    environment:
      - FLASK_APP=/microservice2-app/micro_app.py
    ports:
      - '5003:5002'
    volumes:
      - ./microservice2:/microservice2-app

  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: esortition_voting
  # ports:
  #   - '5432:5432'
