"""Initial commit

Revision ID: 45342305a1fd
Revises: 
Create Date: 2024-03-07 17:02:16.212425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45342305a1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('option', sa.Integer(), nullable=True),
    sa.Column('election_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    # ### end Alembic commands ###
