"""remove unique email

Revision ID: 7559e4fad8fc
Revises: c101c3f2d50f
Create Date: 2024-03-07 16:46:39.905249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7559e4fad8fc'
down_revision = 'c101c3f2d50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.drop_constraint('voter_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voter', schema=None) as batch_op:
        batch_op.create_unique_constraint('voter_email_key', ['email'])

    # ### end Alembic commands ###
