"""revert initial  migration

Revision ID: d8517d3b4286
Revises: 911a60e32178
Create Date: 2024-03-05 17:36:04.659807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8517d3b4286'
down_revision = '911a60e32178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_constraint('election_random_code_key', type_='unique')
        batch_op.drop_column('random_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('election_random_code_key', ['random_code'])

    # ### end Alembic commands ###
