"""remove height again

Revision ID: 0921b731eeed
Revises: 4396944c75a3
Create Date: 2024-03-03 20:13:06.707662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0921b731eeed'
down_revision: Union[str, None] = '4396944c75a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'height')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
