"""add height with nullable

Revision ID: 4396944c75a3
Revises: 5a33234a7a51
Create Date: 2024-03-03 18:22:27.635001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4396944c75a3'
down_revision: Union[str, None] = '5a33234a7a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vote', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vote', 'height')
    # ### end Alembic commands ###
