name: Build and Deploy

on:
  push:
    branches:
      - deployment

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8 app.py

      - name: Run unit tests
        run: pytest test.py

  deploy:
    name: Deploy to Github Container Registry
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log into GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Iterate over directories and build/push images
        run: |
          for dir in */; do
            if [ "$dir" != ".github/" ] && [ "$dir" != "data/" ]; then
              image_name="${dir%/}"
              docker build -t "$image_name:latest" "$dir"
              docker tag "$image_name:latest" "ghcr.io/${{ secrets.GHCR_USERNAME }}/$image_name:latest"
              docker push "ghcr.io/${{ secrets.GHCR_USERNAME }}/$image_name:latest"
            fi
          done